version: "3.8"

services:

  postgres:
    image: postgres:15
    container_name: postgres-t3
    environment:
      POSTGRES_USER: tarea3
      POSTGRES_PASSWORD: tarea3
      POSTGRES_DB: tarea3
    ports:
      - "5432:5432"
    networks:
      - big-data

  bigdata:
    build: .
    container_name: big-data
    ports:
      - "8888:8888"
    volumes:
      - ./notebooks:/src/notebooks
      - ./data:/src/data
      - ./output:/src/output
    working_dir: /src
    depends_on:
      - postgres
    command: >
      jupyter notebook
      --ip=0.0.0.0
      --port=8888
      --no-browser
      --allow-root
    networks:
      - big-data

networks:
  big-data:
    driver: bridge
